# Generated by Django 5.0.3 on 2024-03-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='game',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='game',
        ),
        migrations.AddField(
            model_name='character',
            name='games',
            field=models.ManyToManyField(to='api.game'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='games',
            field=models.ManyToManyField(to='api.game'),
        ),
    ]
