version: '3'

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=SameAsDB_PASSWORD
    ports:
      - "5432:5432"

volumes:
  postgres_data:
